name: Publish composer package to Artifactory

on:
  push:
    tags:
      - v*

jobs:
  publish_tag:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v2
  
      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Create tar file
        run: git archive --format=tar --prefix=${GITHUB_REPOSITORY#neta-io/}/ ${GITHUB_REF##*/} | gzip > ${GITHUB_REF##*/}.tar.gz
      
      - name: Publish to artifactory
        uses: advancedcsg-open/action-jfrog-cli@v1.2.0
        with:
          url: https://artifactory.ops.neta.sh/
          credentials type: 'apikey'
          apikey: ${{ secrets.ARTIFACTORY_API_KEY }}
          args: u ${GITHUB_REF##*/}.tar.gz "/php-local/${GITHUB_REPOSITORY#neta-io/}/${GITHUB_REPOSITORY#neta-io/}-${GITHUB_REF##*/}.tar.gz" --props="composer.version=${GITHUB_REF##*/v}"
      
  notify-if-fail:
    runs-on: ubuntu-latest  
    needs: [publish_tag]
    if: failure()
    steps:
      - uses: rtCamp/action-slack-notify@v2.0.0
        env:
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_COLOR: '#ff4d4d'
          SLACK_ICON: https://github.com/github.png?size=48
          SLACK_TITLE: Failed Workflow
          SLACK_MESSAGE: ${{ github.workflow }}
          SLACK_USERNAME: GitHub Actions
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
